name: Build PHP Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [ "php-fpm" ]
        tag: [ "8.4", "8.3" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./php/Dockerfile
          push: true
          target: ${{ matrix.target }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_VERSION=${{ matrix.tag }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm:${{ matrix.tag }}
            ${{ matrix.tag == '8.4' && format('{0}/php-fpm:latest', secrets.DOCKERHUB_USERNAME) || null}}